services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    # Force the AMD64 image on Apple Silicon hosts; omit on native x64
    platform: "linux/amd64"

volumes:
  sql_data:
